In [1]:
import numpy as np
import pandas as pd
import ast

movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/tmdb_5000_credits.csv')
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1622,30000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,9452,"[{""id"": 3045, ""name"": ""mission of murder""}, {""...",en,Bulworth,A suicidally disillusioned liberal politician ...,4.523630,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1998-05-15,29202884,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Brace yourself. This politician is about to te...,Bulworth,6.3,66
4726,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,9821,"[{""id"": 2494, ""name"": ""ohio""}, {""id"": 10683, ""...",en,The Mighty,This tells the story of a strong friendship be...,5.497682,"[{""name"": ""Miramax Films"", ""id"": 14}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1998-10-23,0,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The quest for friendship is the noblest cause ...,The Mighty,7.1,51
896,51000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 35, ""...",NaN,9907,"[{""id"": 4402, ""name"": ""peasant""}, {""id"": 4932,...",en,Barnyard,"When things get crazy at the farm, it's up to ...",10.430832,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2006-08-04,72779000,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens in the barn stays in the barn,Barnyard,5.3,225
2005,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...",NaN,13579,[],en,The Longshots,"The true story of Jasmine Plummer who, at the ...",4.030724,"[{""name"": ""Cube Vision"", ""id"": 2780}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-08-22,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,The Longshots,6.5,11
3953,0,"[{""id"": 10752, ""name"": ""War""}, {""id"": 18, ""nam...",NaN,281230,"[{""id"": 187056, ""name"": ""woman director""}]",en,Fort McCoy,Unable to serve in World War II because of a h...,0.384496,[],[],2014-01-01,0,0.0,[],Released,NaN,Fort McCoy,6.3,2

In [2]:
movies = movies.merge(credits, on='title')

In [3]:
movies = movies.drop_duplicates(subset='title')

In [4]:
# selects this columns:-  geners, id, keywords, title, overview , cast, crew
ovies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.dropna(inplace=True)

In [5]:
movies = movies.merge(credits, on='title')

movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,tagline,title,vote_average,vote_count,movie_id_x,cast_x,crew_x,movie_id_y,cast_y,crew_y
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies.isnull().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
movie_id_x              0
cast_x                  0
crew_x                  0
movie_id_y              0
cast_y                  0
crew_y                  0
dtype: int64

In [7]:
movies.duplicated().sum()

np.int64(0)

In [8]:
movies.loc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [9]:
movies = movies.drop_duplicates(subset ='title')
movies.head(1)
print(movies.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id_x', 'cast_x', 'crew_x', 'movie_id_y', 'cast_y',
       'crew_y'],
      dtype='object')

In [10]:
#movies = movies[['id','title','overview','genres','keywords','cast','crew']]
movies = movies[['id','title','overview','genres','keywords','cast_x','crew_x']]

In [11]:
movies.head(1)

,id,title,overview,genres,keywords,cast_x,crew_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
movies.dropna(inplace=True)
movies.shape

(1492, 7)

In [13]:
def convert(obj):
    return [i['name'] for i in ast.literal_eval(obj)]

In [14]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [15]:
movies.head(1)

,id,title,overview,genres,keywords,cast_x,crew_x
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [16]:
def convert3(obj):
    obj = ast.literal_eval(obj)
    return [i['name'] for i in obj[:3]]

In [18]:
movies['cast'] = movies['cast_x'].apply(convert3)

In [22]:
movies.head(2)

,id,title,overview,genres,keywords,cast_x,crew_x,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [23]:
def fetch_director(obj):
    obj = ast.literal_eval(obj)

    for i in obj:
        if i['job'] == 'Director':
            return [i['name']]
    return []

In [21]:
movies['crew'] = movies['crew_x'].apply(fetch_director)

In [85]:
movies.head(1)

,id,title,overview,genres,keywords,cast_x,crew_x,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [25]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())  #convert string to list

In [27]:
movies['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [28]:
# space remove kar rahe hain taki words combine ho jaye (better matching ke liye)
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [86]:
movies.head(1)

,id,title,overview,genres,keywords,cast_x,crew_x,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [30]:
# sab columns ko combine karke ek single tags column bana rahe hain
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies[['title','tags']].head(1)

    title                                               tags
0  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...

In [32]:
movies.head(2)

,id,title,overview,genres,keywords,cast_x,crew_x,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [34]:
new_df = movies[['id','title','tags']]

In [35]:
new_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
1487,2292,Clerks,"[Convenience, and, video, store, clerks, Dante..."
1488,255266,Dry Spell,"[Sasha, tries, to, get, her, soon-to-be, ex, h..."
1489,157185,Tin Can Man,"[Recently, dumped, by, his, girlfirend, for, a..."
1490,14337,Primer,"[Friends/fledgling, entrepreneurs, invent, a, ..."
1491,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."

In [36]:
# list ko string me convert kar rahe hain (vectorization ke liye)
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

/tmp/ipykernel_7838/2186852858.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [37]:
new_df.head(2)

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [38]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

/tmp/ipykernel_7838/1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [39]:
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [40]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [41]:
# words ko root form me convert kar rahe hain (similar words match karne ke liye)
def stem(text):
    return " ".join([ps.stem(i) for i in text.split()])

In [42]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_7838/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [43]:
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [44]:
# TF-IDF use kar rahe hain (better accuracy ke liye)
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
vectors = tfidf.fit_transform(new_df['tags']).toarray()

In [45]:
vectors.shape

(1492, 5000)

In [46]:
# cosine similarity calculate kar rahe hain
# ye batata hai ki ek movie dusri movie se kitni similar hai
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [47]:
similarity.shape

(1492, 1492)

In [59]:
#ye function similar movies suggest karega
def recommend(movie):
  index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
  recommended_movies = []
  for i in movies_list[1:6]:
        recommended_movies.append(new_df.iloc[i[0]].title)
  return recommended_movies

In [81]:
recommended = recommend('Batman Begins')
recommended

['The Dark Knight',
 'The Dark Knight Rises',
 'Batman v Superman: Dawn of Justice',
 'The Prestige',
 'Man of Steel']

In [77]:
#correct movie list
relevant_movies = [
    "The Dark Knight",
    "The Dark Knight Rises",
    "Batman v Superman: Dawn of Justice",
    "Man of Steel"
]

In [83]:
def precision_at_k(recommended, relevant, k=5):
    # top k recommended movies select kar rahe hain
    recommended = recommended[:k]

    # correct matches count karne ke liye variable
    count = 0

    # har recommended movie ko check kar rahe hain
    for movie in recommended:
        if movie in relevant:
            count += 1

    # precision = correct predictions / total predictions
    return count / k

In [84]:
score = precision_at_k(recommended,relevant_movies,5)
score

0.8